/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Banner: typeof import('./components/Banner.vue')['default']
    'Carousel ': typeof import('./components/Carousel .vue')['default']

    Header: typeof import('./components/Pcheader.vue')['default']
    PcFooter: typeof import('./components/Pcfooter.vue')['default']
    PcHeader: typeof import('./components/Pcheader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./components/Search.vue')['default']
  }
}
